### ISSUE TITLE
Not run app in TV Simulator but it's run on macOS

### ISSUE THREAD

**Issue by pnilkanth12** [LibertyGlobal/flutter-tvos-demo#4]
Hi, When I try to run app on TV Simulator using `flutter run --dart-define TV_MODE=ON` then it's run in Mac OS not tvOS

Which step I perform:

- Download code
- Change FLUTTER_LOCAL_ENGINE in both file to set my systems download engine path upset out folder keep [Not include out folder name `/Users/pnilkanth12/Development` ]
- flutter run --dart-define TV_MODE=ON 
- run above command in terminal but it's not run in TV Simulator it's run on macOS

**Tried-1**

- when I try to run on Apple TV it's show error 
<img width="943" alt="Screenshot 2023-02-15 at 17 35 56" src="https://user-images.githubusercontent.com/42322220/219023038-c27a51d8-16db-49f6-946b-eda293849b36.png">

**Tried-2**

- When try try to run command `sh scripts/run_apple_tv.sh` then it's remove tvOS folder and open Xcode 
- show error in Android studio and open Xcode
<img width="1021" alt="Screenshot 2023-02-15 at 17 38 47" src="https://user-images.githubusercontent.com/42322220/219023535-1b897e66-af67-46ce-abc9-d710e2844a2a.png">

Thanks in Advance

**Comment by jwoelke** [comment]
The Apple TV flutter test application cannot be started using the "flutter" tools. We did not modify the flutter tools to handle the apple tv target, we only modified the engine. Modifying the flutter tools would require a lot more modifications than we had to do in the engine only. This means that command like flutter build and run will not work.
The application can only be started using xcode as described in the readme.
I assume that you refer to this script https://github.com/DenisovAV/flutter_tv/blob/master/scripts/run_apple_tv.sh which is not part of this demo app. That script follows the steps described in the readme and uses xcode to start the application.
The scripts part of the demo app do not remove the tvos folders, but rename it to ios. This must be done so that the regular flutter tools think they can handle this target. (like flutter pub get.... etc).
The script you use to build relies on "fvm" to be installed. I see in your last screenshot that it is not installed.
If you don't want to use fvm, then simple remove all the "fvm " prefixes of all the flutter commands.
